apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "elasticsearch"
      tier: "infra"
      version: "1"
    name: "elasticsearch"
  spec:
    ports:
    - port: 9200
      protocol: "TCP"
      targetPort: 9200
    selector:
      app: "elasticsearch"
      tier: "infra"
      version: "1"
    type: "LoadBalancer"

- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    labels:
      app: "elasticsearch"
      tier: "infra"
      version: "1"
    name: "elasticsearch"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "elasticsearch"
        tier: "infra"
        version: "1"
    template:
      metadata:
        labels:
          app: "elasticsearch"
          tier: "infra"
          version: "1"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.2"
          name: "elasticsearch"
