apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "kafka"
      tier: "infra"
      version: "1"
    name: "kafka"
  spec:
    ports:
    - port: 9092
      protocol: "TCP"
      targetPort: 9092
    selector:
      app: "kafka"
      tier: "infra"
      version: "1"
    type: "LoadBalancer"

- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    labels:
      app: "kafka"
      tier: "infra"
      version: "1"
    name: "kafka"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "kafka"
        tier: "infra"
        version: "1"
    template:
      metadata:
        labels:
          app: "kafka"
          tier: "infra"
          version: "1"
      spec:
        containers:
        - name: kafka
          image: "bitnami/kafka:2"
          env:
          - name: "KAFKA_ZOOKEEPER_CONNECT"
            value: "zookeeper:2181"
          - name: "ALLOW_PLAINTEXT_LISTENER"
            value: "yes"
          - name: "AUTO_CREATE_TOPICS"
            value: "true"
          - name: "KAFKA_ADVERTISED_LISTENERS"
            value: "PLAINTEXT://kafka:9092"
            #          - name: "KAFKA_ADVERTISED_HOST_NAME"
            #value: "kafka"
