apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/prometheus"
      prometheus.io/port: "9411"
    labels:
      app: "zipkin"
      tier: "infra"
      version: "1"
    name: "zipkin"
  spec:
    ports:
    - port: 9411
      protocol: "TCP"
      targetPort: 9411
    selector:
      app: "zipkin"
      tier: "infra"
      version: "1"
    type: "LoadBalancer"

- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    labels:
      app: "zipkin"
      tier: "infra"
      version: "1"
    name: "zipkin"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "zipkin"
        tier: "infra"
        version: "1"
    template:
      metadata:
        labels:
          app: "zipkin"
          tier: "infra"
          version: "1"
      spec:
        containers:
        - env:
          - name: "ES_HOSTS"
            value: "elasticsearch"
          - name: "STORAGE_TYPE"
            value: "elasticsearch"
          - name: "KAFKA_ZOOKEEPER"
            value: "zookeeper:2181"
          - name: "KAFKA_GROUP_ID"
            value: "zipkin"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "openzipkin/zipkin:2.11.5"
          name: "zipkin"
          # readinessProbe:
          #   httpGet:
          #     path: "/api/v1/services"
          #     port: 9411
          #   initialDelaySeconds: 5
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
