apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "zookeeper"
      tier: "infra"
      version: "1"
    name: "zookeeper"
  spec:
    ports:
    - port: 2181
      protocol: "TCP"
      targetPort: 2181
    selector:
      app: "zookeeper"
      tier: "infra"
      version: "1"
    type: "LoadBalancer"

- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    labels:
      app: "zookeeper"
      tier: "infra"
      version: "1"
    name: "zookeeper"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "zookeeper"
        tier: "infra"
        version: "1"
    template:
      metadata:
        labels:
          app: "zookeeper"
          tier: "infra"
          version: "1"
      spec:
        containers:
        - name: zookeeper
          image: "bitnami/zookeeper:latest"
          env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
